"""Update Station with Fuel model

Revision ID: d28ec0e36dbf
Revises: c6bfd5e4f2d6
Create Date: 2025-05-17 11:46:01.541539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd28ec0e36dbf'
down_revision: Union[str, None] = 'c6bfd5e4f2d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stations', sa.Column('external_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stations', 'external_id')
    # ### end Alembic commands ###
